export const MOCK_CATEGORIES = [
  { id: '1', name: 'Raw Materials' },
  { id: '2', name: 'Machinery & Equipment' },
  { id: '3', name: 'Packaging Solutions' },
  { id: '4', name: 'Electronics Components' },
  { id: '5', name: 'Textiles & Apparel' },
];

export const MOCK_PRODUCTS = [
  {
    id: '1',
    title: 'Industrial Grade Stainless Steel Sheets',
    company_name: 'MetalWorks Global',
    company_id: 'c1',
    category: 'Raw Materials',
    price_range: 'KES 325 - 520 / kg',
    min_order: 500,
    image: 'https://images.unsplash.com/photo-1590487955519-74d30c5e7b24?auto=format&fit=crop&q=80&w=800',
    description: 'High-quality 304 stainless steel sheets suitable for manufacturing and construction.',
    is_featured: true,
  },
  {
    id: '2',
    title: 'Automated Packaging Conveyor System',
    company_name: 'TechPack Solutions',
    company_id: 'c2',
    category: 'Machinery & Equipment',
    price_range: 'KES 1,560,000 - 2,340,000 / unit',
    min_order: 1,
    image: 'https://images.unsplash.com/photo-1587884784915-d419dd1ac5ee?auto=format&fit=crop&q=80&w=800',
    description: 'Customizable conveyor belt system with integrated sorting sensors.',
    is_featured: true,
  },
  {
    id: '3',
    title: 'Eco-friendly Corrugated Boxes',
    company_name: 'GreenBox Co.',
    company_id: 'c3',
    category: 'Packaging Solutions',
    price_range: 'KES 52 - 156 / piece',
    min_order: 2000,
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=800',
    description: '100% recycled packaging materials available in various standard sizes.',
    is_featured: false,
  },
  {
    id: '4',
    title: 'Silicon Microcontrollers (MCU)',
    company_name: 'SiliconDynamics',
    company_id: 'c4',
    category: 'Electronics Components',
    price_range: 'KES 234 - 455 / unit',
    min_order: 10000,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800',
    description: 'Advanced 32-bit microcontrollers for IoT and smart devices.',
    is_featured: false,
  },
  {
    id: '5',
    title: 'Organic Cotton Fabric Roll',
    company_name: 'Loom & Thread',
    company_id: 'c5',
    category: 'Textiles & Apparel',
    price_range: 'KES 585 - 780 / meter',
    min_order: 100,
    image: 'https://images.unsplash.com/photo-1584288070624-9b883d6a2f77?auto=format&fit=crop&q=80&w=800',
    description: 'GOTS certified organic cotton in solid neutral colors.',
    is_featured: true,
  },
  {
    id: '6',
    title: 'Commercial CNC Router Machine',
    company_name: 'Precision CNC',
    company_id: 'c6',
    category: 'Machinery & Equipment',
    price_range: 'KES 5,850,000 - 7,800,000 / unit',
    min_order: 1,
    image: 'https://images.unsplash.com/photo-1620916296316-c9561b3cd355?auto=format&fit=crop&q=80&w=800',
    description: 'High-precision 3-axis CNC router for woodworking and metal fabrication.',
    is_featured: false,
  }
];
